//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ProMasterAssistant.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConnectionsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConnectionsEntities object using the connection string found in the 'ConnectionsEntities' section of the application configuration file.
        /// </summary>
        public ConnectionsEntities() : base("name=ConnectionsEntities", "ConnectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConnectionsEntities object.
        /// </summary>
        public ConnectionsEntities(string connectionString) : base(connectionString, "ConnectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConnectionsEntities object.
        /// </summary>
        public ConnectionsEntities(EntityConnection connection) : base(connection, "ConnectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserConnectionString> UserConnectionStrings
        {
            get
            {
                if ((_UserConnectionStrings == null))
                {
                    _UserConnectionStrings = base.CreateObjectSet<UserConnectionString>("UserConnectionStrings");
                }
                return _UserConnectionStrings;
            }
        }
        private ObjectSet<UserConnectionString> _UserConnectionStrings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserConnectionStrings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserConnectionStrings(UserConnectionString userConnectionString)
        {
            base.AddObject("UserConnectionStrings", userConnectionString);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConnectionsModel", Name="UserConnectionString")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserConnectionString : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserConnectionString object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="connectionName">Initial value of the ConnectionName property.</param>
        /// <param name="connectionString">Initial value of the ConnectionString property.</param>
        /// <param name="isCurrent">Initial value of the IsCurrent property.</param>
        public static UserConnectionString CreateUserConnectionString(global::System.Int32 id, global::System.String userName, global::System.String connectionName, global::System.String connectionString, global::System.Byte isCurrent)
        {
            UserConnectionString userConnectionString = new UserConnectionString();
            userConnectionString.Id = id;
            userConnectionString.UserName = userName;
            userConnectionString.ConnectionName = connectionName;
            userConnectionString.ConnectionString = connectionString;
            userConnectionString.IsCurrent = isCurrent;
            return userConnectionString;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionName
        {
            get
            {
                return _ConnectionName;
            }
            set
            {
                OnConnectionNameChanging(value);
                ReportPropertyChanging("ConnectionName");
                _ConnectionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionName");
                OnConnectionNameChanged();
            }
        }
        private global::System.String _ConnectionName;
        partial void OnConnectionNameChanging(global::System.String value);
        partial void OnConnectionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionString
        {
            get
            {
                return _ConnectionString;
            }
            set
            {
                OnConnectionStringChanging(value);
                ReportPropertyChanging("ConnectionString");
                _ConnectionString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionString");
                OnConnectionStringChanged();
            }
        }
        private global::System.String _ConnectionString;
        partial void OnConnectionStringChanging(global::System.String value);
        partial void OnConnectionStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IsCurrent
        {
            get
            {
                return _IsCurrent;
            }
            set
            {
                OnIsCurrentChanging(value);
                ReportPropertyChanging("IsCurrent");
                _IsCurrent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCurrent");
                OnIsCurrentChanged();
            }
        }
        private global::System.Byte _IsCurrent;
        partial void OnIsCurrentChanging(global::System.Byte value);
        partial void OnIsCurrentChanged();

        #endregion
    
    }

    #endregion
    
}
