//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProMasterAssistant.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProMasterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProMasterEntities object using the connection string found in the 'ProMasterEntities' section of the application configuration file.
        /// </summary>
        public ProMasterEntities() : base("name=ProMasterEntities", "ProMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProMasterEntities object.
        /// </summary>
        public ProMasterEntities(string connectionString) : base(connectionString, "ProMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProMasterEntities object.
        /// </summary>
        public ProMasterEntities(EntityConnection connection) : base(connection, "ProMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_rules> gl_rules
        {
            get
            {
                if ((_gl_rules == null))
                {
                    _gl_rules = base.CreateObjectSet<gl_rules>("gl_rules");
                }
                return _gl_rules;
            }
        }
        private ObjectSet<gl_rules> _gl_rules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_segment_codes> gl_segment_codes
        {
            get
            {
                if ((_gl_segment_codes == null))
                {
                    _gl_segment_codes = base.CreateObjectSet<gl_segment_codes>("gl_segment_codes");
                }
                return _gl_segment_codes;
            }
        }
        private ObjectSet<gl_segment_codes> _gl_segment_codes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_segment_defn> gl_segment_defn
        {
            get
            {
                if ((_gl_segment_defn == null))
                {
                    _gl_segment_defn = base.CreateObjectSet<gl_segment_defn>("gl_segment_defn");
                }
                return _gl_segment_defn;
            }
        }
        private ObjectSet<gl_segment_defn> _gl_segment_defn;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_type> gl_type
        {
            get
            {
                if ((_gl_type == null))
                {
                    _gl_type = base.CreateObjectSet<gl_type>("gl_type");
                }
                return _gl_type;
            }
        }
        private ObjectSet<gl_type> _gl_type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_view_segments> gl_view_segments
        {
            get
            {
                if ((_gl_view_segments == null))
                {
                    _gl_view_segments = base.CreateObjectSet<gl_view_segments>("gl_view_segments");
                }
                return _gl_view_segments;
            }
        }
        private ObjectSet<gl_view_segments> _gl_view_segments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gl_views> gl_views
        {
            get
            {
                if ((_gl_views == null))
                {
                    _gl_views = base.CreateObjectSet<gl_views>("gl_views");
                }
                return _gl_views;
            }
        }
        private ObjectSet<gl_views> _gl_views;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_rules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_rules(gl_rules gl_rules)
        {
            base.AddObject("gl_rules", gl_rules);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_segment_codes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_segment_codes(gl_segment_codes gl_segment_codes)
        {
            base.AddObject("gl_segment_codes", gl_segment_codes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_segment_defn EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_segment_defn(gl_segment_defn gl_segment_defn)
        {
            base.AddObject("gl_segment_defn", gl_segment_defn);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_type(gl_type gl_type)
        {
            base.AddObject("gl_type", gl_type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_view_segments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_view_segments(gl_view_segments gl_view_segments)
        {
            base.AddObject("gl_view_segments", gl_view_segments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gl_views EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogl_views(gl_views gl_views)
        {
            base.AddObject("gl_views", gl_views);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_rules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_rules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_rules object.
        /// </summary>
        /// <param name="gl_type">Initial value of the gl_type property.</param>
        /// <param name="view_name">Initial value of the view_name property.</param>
        /// <param name="search_order">Initial value of the search_order property.</param>
        /// <param name="segments">Initial value of the segments property.</param>
        /// <param name="operator">Initial value of the operator property.</param>
        /// <param name="erromsg">Initial value of the erromsg property.</param>
        public static gl_rules Creategl_rules(global::System.String gl_type, global::System.String view_name, global::System.Int32 search_order, global::System.String segments, global::System.String @operator, global::System.String erromsg)
        {
            gl_rules gl_rules = new gl_rules();
            gl_rules.gl_type = gl_type;
            gl_rules.view_name = view_name;
            gl_rules.search_order = search_order;
            gl_rules.segments = segments;
            gl_rules.@operator = @operator;
            gl_rules.erromsg = erromsg;
            return gl_rules;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gl_type
        {
            get
            {
                return _gl_type;
            }
            set
            {
                if (_gl_type != value)
                {
                    Ongl_typeChanging(value);
                    ReportPropertyChanging("gl_type");
                    _gl_type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gl_type");
                    Ongl_typeChanged();
                }
            }
        }
        private global::System.String _gl_type;
        partial void Ongl_typeChanging(global::System.String value);
        partial void Ongl_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String view_name
        {
            get
            {
                return _view_name;
            }
            set
            {
                if (_view_name != value)
                {
                    Onview_nameChanging(value);
                    ReportPropertyChanging("view_name");
                    _view_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("view_name");
                    Onview_nameChanged();
                }
            }
        }
        private global::System.String _view_name;
        partial void Onview_nameChanging(global::System.String value);
        partial void Onview_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 search_order
        {
            get
            {
                return _search_order;
            }
            set
            {
                if (_search_order != value)
                {
                    Onsearch_orderChanging(value);
                    ReportPropertyChanging("search_order");
                    _search_order = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("search_order");
                    Onsearch_orderChanged();
                }
            }
        }
        private global::System.Int32 _search_order;
        partial void Onsearch_orderChanging(global::System.Int32 value);
        partial void Onsearch_orderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String segments
        {
            get
            {
                return _segments;
            }
            set
            {
                OnsegmentsChanging(value);
                ReportPropertyChanging("segments");
                _segments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("segments");
                OnsegmentsChanged();
            }
        }
        private global::System.String _segments;
        partial void OnsegmentsChanging(global::System.String value);
        partial void OnsegmentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @operator
        {
            get
            {
                return _operator;
            }
            set
            {
                OnoperatorChanging(value);
                ReportPropertyChanging("operator");
                _operator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("operator");
                OnoperatorChanged();
            }
        }
        private global::System.String _operator;
        partial void OnoperatorChanging(global::System.String value);
        partial void OnoperatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String erromsg
        {
            get
            {
                return _erromsg;
            }
            set
            {
                OnerromsgChanging(value);
                ReportPropertyChanging("erromsg");
                _erromsg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("erromsg");
                OnerromsgChanged();
            }
        }
        private global::System.String _erromsg;
        partial void OnerromsgChanging(global::System.String value);
        partial void OnerromsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message2
        {
            get
            {
                return _message2;
            }
            set
            {
                Onmessage2Changing(value);
                ReportPropertyChanging("message2");
                _message2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message2");
                Onmessage2Changed();
            }
        }
        private global::System.String _message2;
        partial void Onmessage2Changing(global::System.String value);
        partial void Onmessage2Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_segment_codes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_segment_codes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_segment_codes object.
        /// </summary>
        /// <param name="segment_id">Initial value of the segment_id property.</param>
        /// <param name="code">Initial value of the code property.</param>
        public static gl_segment_codes Creategl_segment_codes(global::System.Int32 segment_id, global::System.String code)
        {
            gl_segment_codes gl_segment_codes = new gl_segment_codes();
            gl_segment_codes.segment_id = segment_id;
            gl_segment_codes.code = code;
            return gl_segment_codes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 segment_id
        {
            get
            {
                return _segment_id;
            }
            set
            {
                if (_segment_id != value)
                {
                    Onsegment_idChanging(value);
                    ReportPropertyChanging("segment_id");
                    _segment_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("segment_id");
                    Onsegment_idChanged();
                }
            }
        }
        private global::System.Int32 _segment_id;
        partial void Onsegment_idChanging(global::System.Int32 value);
        partial void Onsegment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                if (_code != value)
                {
                    OncodeChanging(value);
                    ReportPropertyChanging("code");
                    _code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("code");
                    OncodeChanged();
                }
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attrib1
        {
            get
            {
                return _attrib1;
            }
            set
            {
                Onattrib1Changing(value);
                ReportPropertyChanging("attrib1");
                _attrib1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attrib1");
                Onattrib1Changed();
            }
        }
        private global::System.String _attrib1;
        partial void Onattrib1Changing(global::System.String value);
        partial void Onattrib1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attrib2
        {
            get
            {
                return _attrib2;
            }
            set
            {
                Onattrib2Changing(value);
                ReportPropertyChanging("attrib2");
                _attrib2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attrib2");
                Onattrib2Changed();
            }
        }
        private global::System.String _attrib2;
        partial void Onattrib2Changing(global::System.String value);
        partial void Onattrib2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attrib3
        {
            get
            {
                return _attrib3;
            }
            set
            {
                Onattrib3Changing(value);
                ReportPropertyChanging("attrib3");
                _attrib3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attrib3");
                Onattrib3Changed();
            }
        }
        private global::System.String _attrib3;
        partial void Onattrib3Changing(global::System.String value);
        partial void Onattrib3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attrib4
        {
            get
            {
                return _attrib4;
            }
            set
            {
                Onattrib4Changing(value);
                ReportPropertyChanging("attrib4");
                _attrib4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attrib4");
                Onattrib4Changed();
            }
        }
        private global::System.String _attrib4;
        partial void Onattrib4Changing(global::System.String value);
        partial void Onattrib4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String active_flag
        {
            get
            {
                return _active_flag;
            }
            set
            {
                Onactive_flagChanging(value);
                ReportPropertyChanging("active_flag");
                _active_flag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("active_flag");
                Onactive_flagChanged();
            }
        }
        private global::System.String _active_flag;
        partial void Onactive_flagChanging(global::System.String value);
        partial void Onactive_flagChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_segment_defn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_segment_defn : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_segment_defn object.
        /// </summary>
        /// <param name="gl_type">Initial value of the gl_type property.</param>
        /// <param name="segment_id">Initial value of the segment_id property.</param>
        /// <param name="error_text">Initial value of the error_text property.</param>
        /// <param name="label">Initial value of the label property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="char_limit">Initial value of the char_limit property.</param>
        /// <param name="width">Initial value of the width property.</param>
        /// <param name="data_type">Initial value of the data_type property.</param>
        /// <param name="validation_type">Initial value of the validation_type property.</param>
        public static gl_segment_defn Creategl_segment_defn(global::System.String gl_type, global::System.Int32 segment_id, global::System.String error_text, global::System.String label, global::System.String name, global::System.Int32 char_limit, global::System.Int32 width, global::System.String data_type, global::System.String validation_type)
        {
            gl_segment_defn gl_segment_defn = new gl_segment_defn();
            gl_segment_defn.gl_type = gl_type;
            gl_segment_defn.segment_id = segment_id;
            gl_segment_defn.error_text = error_text;
            gl_segment_defn.label = label;
            gl_segment_defn.name = name;
            gl_segment_defn.char_limit = char_limit;
            gl_segment_defn.width = width;
            gl_segment_defn.data_type = data_type;
            gl_segment_defn.validation_type = validation_type;
            return gl_segment_defn;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gl_type
        {
            get
            {
                return _gl_type;
            }
            set
            {
                if (_gl_type != value)
                {
                    Ongl_typeChanging(value);
                    ReportPropertyChanging("gl_type");
                    _gl_type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gl_type");
                    Ongl_typeChanged();
                }
            }
        }
        private global::System.String _gl_type;
        partial void Ongl_typeChanging(global::System.String value);
        partial void Ongl_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 segment_id
        {
            get
            {
                return _segment_id;
            }
            set
            {
                if (_segment_id != value)
                {
                    Onsegment_idChanging(value);
                    ReportPropertyChanging("segment_id");
                    _segment_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("segment_id");
                    Onsegment_idChanged();
                }
            }
        }
        private global::System.Int32 _segment_id;
        partial void Onsegment_idChanging(global::System.Int32 value);
        partial void Onsegment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String error_text
        {
            get
            {
                return _error_text;
            }
            set
            {
                Onerror_textChanging(value);
                ReportPropertyChanging("error_text");
                _error_text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("error_text");
                Onerror_textChanged();
            }
        }
        private global::System.String _error_text;
        partial void Onerror_textChanging(global::System.String value);
        partial void Onerror_textChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String label
        {
            get
            {
                return _label;
            }
            set
            {
                OnlabelChanging(value);
                ReportPropertyChanging("label");
                _label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("label");
                OnlabelChanged();
            }
        }
        private global::System.String _label;
        partial void OnlabelChanging(global::System.String value);
        partial void OnlabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 char_limit
        {
            get
            {
                return _char_limit;
            }
            set
            {
                Onchar_limitChanging(value);
                ReportPropertyChanging("char_limit");
                _char_limit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("char_limit");
                Onchar_limitChanged();
            }
        }
        private global::System.Int32 _char_limit;
        partial void Onchar_limitChanging(global::System.Int32 value);
        partial void Onchar_limitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 width
        {
            get
            {
                return _width;
            }
            set
            {
                OnwidthChanging(value);
                ReportPropertyChanging("width");
                _width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("width");
                OnwidthChanged();
            }
        }
        private global::System.Int32 _width;
        partial void OnwidthChanging(global::System.Int32 value);
        partial void OnwidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data_type
        {
            get
            {
                return _data_type;
            }
            set
            {
                Ondata_typeChanging(value);
                ReportPropertyChanging("data_type");
                _data_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("data_type");
                Ondata_typeChanged();
            }
        }
        private global::System.String _data_type;
        partial void Ondata_typeChanging(global::System.String value);
        partial void Ondata_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String validation_type
        {
            get
            {
                return _validation_type;
            }
            set
            {
                Onvalidation_typeChanging(value);
                ReportPropertyChanging("validation_type");
                _validation_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("validation_type");
                Onvalidation_typeChanged();
            }
        }
        private global::System.String _validation_type;
        partial void Onvalidation_typeChanging(global::System.String value);
        partial void Onvalidation_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_sql
        {
            get
            {
                return _search_sql;
            }
            set
            {
                Onsearch_sqlChanging(value);
                ReportPropertyChanging("search_sql");
                _search_sql = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("search_sql");
                Onsearch_sqlChanged();
            }
        }
        private global::System.String _search_sql;
        partial void Onsearch_sqlChanging(global::System.String value);
        partial void Onsearch_sqlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> row_warn
        {
            get
            {
                return _row_warn;
            }
            set
            {
                Onrow_warnChanging(value);
                ReportPropertyChanging("row_warn");
                _row_warn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_warn");
                Onrow_warnChanged();
            }
        }
        private Nullable<global::System.Int32> _row_warn;
        partial void Onrow_warnChanging(Nullable<global::System.Int32> value);
        partial void Onrow_warnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_win_defn
        {
            get
            {
                return _search_win_defn;
            }
            set
            {
                Onsearch_win_defnChanging(value);
                ReportPropertyChanging("search_win_defn");
                _search_win_defn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("search_win_defn");
                Onsearch_win_defnChanged();
            }
        }
        private global::System.String _search_win_defn;
        partial void Onsearch_win_defnChanging(global::System.String value);
        partial void Onsearch_win_defnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_type object.
        /// </summary>
        /// <param name="gl_type1">Initial value of the gl_type1 property.</param>
        /// <param name="delimiter">Initial value of the delimiter property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static gl_type Creategl_type(global::System.String gl_type1, global::System.String delimiter, global::System.String description, global::System.String status)
        {
            gl_type gl_type = new gl_type();
            gl_type.gl_type1 = gl_type1;
            gl_type.delimiter = delimiter;
            gl_type.description = description;
            gl_type.status = status;
            return gl_type;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gl_type1
        {
            get
            {
                return _gl_type1;
            }
            set
            {
                if (_gl_type1 != value)
                {
                    Ongl_type1Changing(value);
                    ReportPropertyChanging("gl_type1");
                    _gl_type1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gl_type1");
                    Ongl_type1Changed();
                }
            }
        }
        private global::System.String _gl_type1;
        partial void Ongl_type1Changing(global::System.String value);
        partial void Ongl_type1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String delimiter
        {
            get
            {
                return _delimiter;
            }
            set
            {
                OndelimiterChanging(value);
                ReportPropertyChanging("delimiter");
                _delimiter = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("delimiter");
                OndelimiterChanged();
            }
        }
        private global::System.String _delimiter;
        partial void OndelimiterChanging(global::System.String value);
        partial void OndelimiterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tab_no
        {
            get
            {
                return _tab_no;
            }
            set
            {
                Ontab_noChanging(value);
                ReportPropertyChanging("tab_no");
                _tab_no = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tab_no");
                Ontab_noChanged();
            }
        }
        private Nullable<global::System.Int32> _tab_no;
        partial void Ontab_noChanging(Nullable<global::System.Int32> value);
        partial void Ontab_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String validation_type
        {
            get
            {
                return _validation_type;
            }
            set
            {
                Onvalidation_typeChanging(value);
                ReportPropertyChanging("validation_type");
                _validation_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("validation_type");
                Onvalidation_typeChanged();
            }
        }
        private global::System.String _validation_type;
        partial void Onvalidation_typeChanging(global::System.String value);
        partial void Onvalidation_typeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_view_segments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_view_segments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_view_segments object.
        /// </summary>
        /// <param name="gl_type">Initial value of the gl_type property.</param>
        /// <param name="view_name">Initial value of the view_name property.</param>
        /// <param name="segment_id">Initial value of the segment_id property.</param>
        /// <param name="position">Initial value of the position property.</param>
        /// <param name="required">Initial value of the required property.</param>
        public static gl_view_segments Creategl_view_segments(global::System.String gl_type, global::System.String view_name, global::System.Int32 segment_id, global::System.Int32 position, global::System.String required)
        {
            gl_view_segments gl_view_segments = new gl_view_segments();
            gl_view_segments.gl_type = gl_type;
            gl_view_segments.view_name = view_name;
            gl_view_segments.segment_id = segment_id;
            gl_view_segments.position = position;
            gl_view_segments.required = required;
            return gl_view_segments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gl_type
        {
            get
            {
                return _gl_type;
            }
            set
            {
                if (_gl_type != value)
                {
                    Ongl_typeChanging(value);
                    ReportPropertyChanging("gl_type");
                    _gl_type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gl_type");
                    Ongl_typeChanged();
                }
            }
        }
        private global::System.String _gl_type;
        partial void Ongl_typeChanging(global::System.String value);
        partial void Ongl_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String view_name
        {
            get
            {
                return _view_name;
            }
            set
            {
                if (_view_name != value)
                {
                    Onview_nameChanging(value);
                    ReportPropertyChanging("view_name");
                    _view_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("view_name");
                    Onview_nameChanged();
                }
            }
        }
        private global::System.String _view_name;
        partial void Onview_nameChanging(global::System.String value);
        partial void Onview_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 segment_id
        {
            get
            {
                return _segment_id;
            }
            set
            {
                if (_segment_id != value)
                {
                    Onsegment_idChanging(value);
                    ReportPropertyChanging("segment_id");
                    _segment_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("segment_id");
                    Onsegment_idChanged();
                }
            }
        }
        private global::System.Int32 _segment_id;
        partial void Onsegment_idChanging(global::System.Int32 value);
        partial void Onsegment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.Int32 _position;
        partial void OnpositionChanging(global::System.Int32 value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dw_expression
        {
            get
            {
                return _dw_expression;
            }
            set
            {
                Ondw_expressionChanging(value);
                ReportPropertyChanging("dw_expression");
                _dw_expression = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dw_expression");
                Ondw_expressionChanged();
            }
        }
        private global::System.String _dw_expression;
        partial void Ondw_expressionChanging(global::System.String value);
        partial void Ondw_expressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String required
        {
            get
            {
                return _required;
            }
            set
            {
                OnrequiredChanging(value);
                ReportPropertyChanging("required");
                _required = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("required");
                OnrequiredChanged();
            }
        }
        private global::System.String _required;
        partial void OnrequiredChanging(global::System.String value);
        partial void OnrequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_sql
        {
            get
            {
                return _search_sql;
            }
            set
            {
                Onsearch_sqlChanging(value);
                ReportPropertyChanging("search_sql");
                _search_sql = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("search_sql");
                Onsearch_sqlChanged();
            }
        }
        private global::System.String _search_sql;
        partial void Onsearch_sqlChanging(global::System.String value);
        partial void Onsearch_sqlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String search_win_defn
        {
            get
            {
                return _search_win_defn;
            }
            set
            {
                Onsearch_win_defnChanging(value);
                ReportPropertyChanging("search_win_defn");
                _search_win_defn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("search_win_defn");
                Onsearch_win_defnChanged();
            }
        }
        private global::System.String _search_win_defn;
        partial void Onsearch_win_defnChanging(global::System.String value);
        partial void Onsearch_win_defnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProMasterModel", Name="gl_views")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gl_views : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gl_views object.
        /// </summary>
        /// <param name="gl_type">Initial value of the gl_type property.</param>
        /// <param name="view_name">Initial value of the view_name property.</param>
        /// <param name="load_order">Initial value of the load_order property.</param>
        public static gl_views Creategl_views(global::System.String gl_type, global::System.String view_name, global::System.Int32 load_order)
        {
            gl_views gl_views = new gl_views();
            gl_views.gl_type = gl_type;
            gl_views.view_name = view_name;
            gl_views.load_order = load_order;
            return gl_views;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gl_type
        {
            get
            {
                return _gl_type;
            }
            set
            {
                if (_gl_type != value)
                {
                    Ongl_typeChanging(value);
                    ReportPropertyChanging("gl_type");
                    _gl_type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gl_type");
                    Ongl_typeChanged();
                }
            }
        }
        private global::System.String _gl_type;
        partial void Ongl_typeChanging(global::System.String value);
        partial void Ongl_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String view_name
        {
            get
            {
                return _view_name;
            }
            set
            {
                if (_view_name != value)
                {
                    Onview_nameChanging(value);
                    ReportPropertyChanging("view_name");
                    _view_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("view_name");
                    Onview_nameChanged();
                }
            }
        }
        private global::System.String _view_name;
        partial void Onview_nameChanging(global::System.String value);
        partial void Onview_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 load_order
        {
            get
            {
                return _load_order;
            }
            set
            {
                Onload_orderChanging(value);
                ReportPropertyChanging("load_order");
                _load_order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("load_order");
                Onload_orderChanged();
            }
        }
        private global::System.Int32 _load_order;
        partial void Onload_orderChanging(global::System.Int32 value);
        partial void Onload_orderChanged();

        #endregion

    
    }

    #endregion

    
}
